xotahal/react-native-material-ui

- lib/Toolbar.js
- package.json
There are 3 different commits on this PR.
https://github.com/xotahal/react-native-material-ui/pull/11/commits/516722f58c610af75354d5ce3dbdd67c1df85846
The old version `1.0.3` cause an error with the old react version,like this
This is tested with the latest `react-native` build `0.29`
Another option is to make the user install it as separate dependency so they can update without a problem. There is an [easy setup](https://github.com/oblador/react-native-vector-icons#android) for this
----
https://github.com/xotahal/react-native-material-ui/pull/11/commits/fdbf886477b82ec4007cf8a780401396b7bb4c65
Which actually reverts your previous commit https://github.com/xotahal/react-native-material-ui/blob/9a0c57511ea871dc6f167871707e29de80167a57/lib/Toolbar.js
Which also I applied a fix to align the …
> Update react-native-vector-icons dependency to 2.0.3, fix warning for TouchableWithoutFeedback and right PropTypes for the Toolbar style property

- lib/Drawer/Section.js
This will fix the bug on the section component of the drawer. If you only have 1 item on a single section component, It will take too much space to render the second section component and somehow the height being is unknown. The culprit is the **flex** style property.
Take a look at this code
```
<Drawer.Section
items={[{
icon: 'playlist-add-check',
value: 'Todos',
label: '0'
}]}
/>
<Divider/>
<Drawer.Section
items={[{
icon: 'settings',
value: 'Settings'
}, {
icon: 'info',
value: 'About'
}, {
icon: 'power-settings-new',
value: 'Logout'
}]}
/>
</Drawer>
```
It looks like this this
and this is the final form after the changes. They stack pretty well.
> Drawer: removed flex style property on section component

- README.md
Added a better way to link packages, since 0.31 with this [PR](https://github.com/facebook/react-native/commit/e8b508144fdcdea436cf4d80d99daec757505c70) of react native they merge [rnpm](https://github.com/rnpm/rnpm) to the core. This is the safest way to install and link packages with your current app build.
You can look my [forked repo](https://github.com/kenma9123/react-native-material-ui) for README.md preview.
> Update readme to add the recommended way of linking packages like react-native-vector-icons

- src/Toolbar/Toolbar.react.js
> Fix leftElement to work with any element and not just icon names

- src/Toolbar/Toolbar.react.js
All platforms (iOS, android and 3rd party windows) implements BackAndroid (iOS mocks it).
Tested and working fine! I'm going to publish it to iOS today!
(I made a new PR because the first one I edited in github directly :P. Also, I'm @meiraleal from other issues, I changed my handler).
> Remove code specific to Android in Toolbar Search

- src/BottomNavigation/BottomNavigationAction.react.js
> [BottomNavigation] Ability to handle custom Icons instead of icon names.

- src/RippleFeedback/RippleFeedback.react.js
Using TouchableOpacity for RippleFeedback, on iOS, provides good visual feedback for touches.
https://facebook.github.io/react-native/docs/touchableopacity.html
> [RippleFeedback] Use TouchableOpacity for iOS (#41)

- src/Button/Button.react.js
Allows to pass `upperCase` property on `Button` component.  Leaving upper case text by default.
> Button: set button text to go uppercase or not

- src/Avatar/Avatar.react.js
I implemented options to pass iconSize and iconColor as props to Avatar. If they are present, they will be used, else it will fall back to prior logic.
> avatarIconProps

- src/ListItem/ListItem.react.js
Added the option to start a third line of text in the ListItem instead of having it automatically wrapped.
> Added tertiaryText Option

- src/ListItem/ListItem.react.js
Deleted the previous pull request, only one commit now. Sorry for the confusion!
> [ListItem] Added Dynamic Text functionality with tertiaryText prop

- src/Button/Button.react.js
- src/Button/__test__/__snapshots__/Button.test.js.snap
- src/styles/getTheme.js
For needs to create something like
> [Button] Ability to set custom icon element instead of name. Ability to set icon styles.

- README.md
- docs/Avatar.md
This will add documentation for the Avatar component. This component is pretty hefty, so it's nice to have some documentation and usage examples in order to see exactly how it can be used.
> Add Avatar documentation

- src/Toolbar/RightElement.react.js
Fix issue #47
We need to clear `result` to hide other icons when `isSearchActive` is true.
> Fix issue #47

- package.json
I have two versions of react-native-vector-icons installed in my project because it's a dependency in this project.
react-native-vector-icon should really be a peerDependency and let the project's package.json dictate the version to use.
cc @xotahal
> make react-native-vector-icons a peerDependencies

- src/Toolbar/CenterElement.react.js
Fix issue #74 
```
<Toolbar
rightElement={<BorderedButton accent text="follow" />}
/>
```
if `centerElement` prop is not specified, for example, `CenterElement` component returns `null`.
I think that cause the problem. So, I have just removed below source.
```
if (!content) {
return null;
}
```
> Fix issue #74

- src/styles/getTheme.js
The `fontFamily` style attribute that the user provides through `ThemeProvider.uiTheme.fontFamily` is not used in the title of `Toolbar` or `Dialog`.
This problem might also arise in other situations.
> Added user supplied fontFamily to Toolbar and Dialog title

- src/Toolbar/Toolbar.react.js
Gracefully deprecates BackAndroid with support for versions going forward as well as older versions.
Proper fix for #139
> Graceful deprecation for BackAndroid

- src/Toolbar/CenterElement.react.js
- src/Toolbar/Toolbar.react.js
when search is active and then toolbar updates which disables search, we need to properly close the search bar other wise the app crashes.
cc @xotahal
> properly close the search on updates

- src/Button/Button.react.js
Button's container style prop type should've been ViewPropTypes.style instead of ViewPropTypes
> Fixed bug for missing ViewPropTypes.style

- src/RadioButton/RadioButton.react.js
The `RadioButton` is expecting `onSelect` and is not using it currently. It only works if we pass down `onCheck` to props as `Checkbox` uses that.
> [RadioButton]: Use onPress function from RadioButton

- src/ListItem/ListItem.react.js
The changes in https://github.com/xotahal/react-native-material-ui/commit/4e2b50813ac8f837da5e288a5ef6dc0c289feac1#diff-94989ecb7ebebf42e6f88f836eb60698 broke the ListItem component and it now shows a warning.
This PR makes the name property optional
> Fix IconToggle in ListItem

- src/Toolbar/RightElement.react.js
Currently just using the Toolbar with throws a proptypes error for the `searchable` prop on `RightElement`. This PR makes the searchable prop optional on the RightElement component
> Searchable prop optional

- src/ActionButton/ActionButton.react.js
Current implementation of action button has hardcoded ripple color. I would like to provide a prop to change it.
> Add ripple color option for action button

- src/Toolbar/Toolbar.react.js
Currently it makes back button unresponsive if you open the search bar a close it.
> Fix back button listener in Toolbar

- src/Dialog/Dialog.react.js
The same problem as https://github.com/xotahal/react-native-material-ui/pull/209
Buttons and other components inside Dialog cannot be pressed.
> Fix dialog subview clicks

- src/ListItem/ListItem.react.js
This PR fixes right element click, which I previously ruined with #195 (sorry for the regression!)
Basically, it returns default `pointerEvents` prop value to the `ListItem` view when the right element is present. Otherwise, it will be `box-only`.
Unfortunately, I cannot find more elegant solution right now.
> Fix list item subview clicks

- src/ListItem/ListItem.react.js
- src/Toolbar/RightElement.react.js
Currently the default Toolbar menu button's icon can't be overwritten, despite the menu.icon props suggesting that I should be. This PR would fix the issue.
> Allow the default menu icon to be overwritten as the props would suggest

- src/Toolbar/LeftElement.react.js
It should show back icon instead of forward icon.
Current design:
> Toolbar search without leftElement shows forward icon

- src/RippleFeedback/RippleFeedback.react.js
TouchableOpacity was used before but it looks strange if only the opacity changes.
> Ripple effect is neither supported by react-native-web

- src/styles/getPlatformElevation.ios.js
I think the shadow radius should be divided by 2 and the offset height should be 1. We should also reset the shadow color to transparent if there is no elevation.
And also it should be possible to set the elevation to 0. Currently it cannot be set to 0 e. g. for _Card_ component because it's always overwritten with theme styles which set the shadows.
Results:
> Fix shadow props on iOS

- src/styles/getPlatformElevation.ios.js
The zIndex should be 0 if there is no elevation.
> Fix iOS zero elevation zIndex

- src/Badge/Badge.react.js
This commit(https://github.com/xotahal/react-native-material-ui/commit/4e2b50813ac8f837da5e288a5ef6dc0c289feac1) changed the default badge size to 4 which breaks because by default in the style we set the width to 16(https://github.com/xotahal/react-native-material-ui/blob/master/src/styles/getTheme.js#L123).
Also the container is set to use top: -8 which is 16/2.
This restores the previous behavior and ensures that badge is visible when size is not provided.
cc @xotahal
> fix default size for a badge

- src/Card/Card.react.js
- src/RippleFeedback/RippleFeedbackAndroid.react.js
7701dee00dbdfc8ba4006d1bd43d5f8919f11290 fixed styling issues with the ripple. It also introduced a bug where if the card had children that were buttons or other elements that could receive input they would never receive the input.
This checks whether the Card has an onPress, and if it does set the pointerEvents to 'box-only', else set it to 'box-none'. 'box-only' implies that only the view itself can receive input, and no children. 'box-none' implies that the view itself won't receive input, and only the children.
> Children in cards might receive input. and fixed backwards compatibility.

- src/Toolbar/CenterElement.react.js
autoCapitalize can have the following values: 'none', 'sentences', 'words', 'characters'. See https://facebook.github.io/react-native/docs/textinput.html for details.
> fix: autoCapitalize is a string

- src/Drawer/Drawer.react.js
I'm getting the following error using "react-native": "0.51.0" (copied styles thing from `Dialog/Dialog.react.js`)
```
FAIL  Tests/Containers/SplashTest.js
● Test suite failed to run
TypeError: Cannot read property 'style' of undefined
at Object.<anonymous> (node_modules/react-native-material-ui/src/Drawer/Drawer.react.js:14:45)
at Object.<anonymous> (node_modules/react-native-material-ui/src/Drawer/index.js:1:159)
at Object.<anonymous> (node_modules/react-native-material-ui/src/index.js:17:25)
```
> fix for undefined ScrollView.propTypes

- src/IconToggle/IconToggle.react.js
I don't know why it was disabled on iOS, but I tried it and it works just fine (and even better).
> perf(IconToggle): Enable native animation on iOS

- src/ActionButton/ActionButton.react.js
Currently elements are allowed as ActionButton icons, but the propType only allows strings.
> Change ActionButton propTypes to allow elements for icons

- src/Drawer/Section.react.js
It's possible to show a variety of list items with the same icon (`star-border` vs `star` for example). This causes errors and can be avoided by allowing users to specify a key instead of defaulting to the icon.
> Duplicate keys when re-using icons

- src/ActionButton/ActionButton.react.js
The default ripple effect color is #AAF (violet) even when the button is red.
> Fix action button’s default ripple effect color

- docs/Toolbar.md
- src/Toolbar/Toolbar.react.js
Currently with animation, the Toolbar's searchable `onSearchClosed` fires after the animation is complete. However there's no way to get when the user has selected the close action.
This PR introduces the `onSearchCloseRequested` prop to be able to listen that event.
The example below shows the use of `onSearchClosed` as compared to `onSearchCloseRequested` to clear the input of the searchable.
**Before:**
**After:**
> Add onSearchCloseRequested prop

- src/IconToggle/IconToggle.react.js
> Make IconToggle name optional - when using children

- src/Snackbar/Snackbar.react.js
- src/styles/getTheme.js
- src/styles/spacing.js
- the material design guidelines has changed: https://material.io/design/components/snackbars.html , the animation is different
- it should be possible to have a snackbar with multiple lines and a dynamic height (then we need to know the height, that's why I've added onHeightChange)
- it should be possible to hide the snackbar on press
> Update snackbar to follow new material guidelines, to support onPress and dynamic height

- src/utils/index.js
I removed BackAndroid import from `utils/index.js` since it is not supported by `react-native` and throws some errors now.
> BackAndroid is not supported anymore in react-native

- src/IconToggle/IconToggle.react.js
TouchableWithoutFeedback's onPressIn and onPressOut props are not cancelled when a user scrolls. IconToggle was previously calling its onPress prop in a handler for TouchableWithoutFeedback's onPressOut prop. As a result, the consumer-specified onPress handler would not abort if the user initiated scroll events.
This commit moves IconToggle's onPress logic to a TouchableWithoutFeedbacks's onPress handler, causing it to abort if a user scrolls.
Fixes xotahal/react-native-material-ui/issues/382
> IconToggle: abort onPress if the user scrolls

- src/Drawer/Section.react.js
- src/ListItem/ListItem.react.js
See https://github.com/xotahal/react-native-material-ui/issues/358
If secondaryText or tertiaryText are empty strings they evaluate as false.
`'' && someCode()` never runs someCode()
In this case this means that secondaryText (whose value is '') gets put directly into the textViewContainer instead of being wrapped in `<Text></Text>` tags.
You can see the original React Native issue and a comment about this solution here https://github.com/facebook/react-native/issues/13243#issuecomment-335488473
> Fix Android shadow node issue (#358)

- docs/Drawer.md
- src/Drawer/Drawer.react.js
In my app it's nice to be able to set `contentContainerStyle={{ height: '100%' }}` so that items inside the drawer can flex grow and allow for positioning of items at the bottom of the drawer
> Add contentContainer style option to Drawer
