xotahal/react-native-material-ui

src/BottomNavigation/BottomNavigationAction.react.js
src/styles/getTheme.js

With these we can simply customize the theme for active buttons for the bottom android navi.

BottomNavigation: able to change the styles of active navigation via theme

---

src/Toolbar/Toolbar.react.js

Changed the propTypes to View.propTypes so that the project integrates with react-native-mocks cleanly for testing.

Prop types

---

docs/Button.md

There is missing prop `upperCase`.
Also, I added `disabled` button example and defaultProps.

Add missing props in Button.md

---

src/Badge/Badge.react.js

Fix PropTypes typo in Badge

---

README.md
docs/Card.md

Currently there is no documentation for the Card component, one of the most popular components in my experience. This will add some basic documentation so people can get started using it without having to dig around in the source too much, even though it's pretty easy to use.

Add Card documentation

---

src/Drawer/Section.react.js

[Drawer] Ability to set custom React element for Drawer Section value

[Drawer] Ability to set custom React element for Drawer Section value

---

package.json

Fix package.json parse error

---

README.md

Fix markdown to appear example images.

---

src/Snackbar/Snackbar.react.js
src/Snackbar/index.js
src/index.js
src/styles/colors.js
src/styles/getTheme.js
src/styles/spacing.js

Hey just created the Snackbar component, it works really good with the bottom navigation component. and follows the [guidelines](https://material.io/guidelines/components/snackbars-toasts.html), still want the implement the multiline version but we can roll out the one line version first.
Please feel free to come up with improvements, I'm checking for PRs at least twice a day.
PS @xotahal could you explain how I get the button styles for this component from getThemes function?

[Snackbar] Added new component

---

README.md

Adds instructions for Roboto

---

README.md

Correct link for custom fonts

---

src/Dialog/DialogDefaultActions.react.js
src/Dialog/DialogStackedActions.react.js
src/ListItem/ListItem.react.js

Fixes lint errors on ci that make every PR fail.

Fixes lint errors on Circle Ci

---

src/RippleFeedback/RippleFeedback.react.js
src/styles/getPlatformElevation.android.js
src/styles/getPlatformElevation.ios.js
src/styles/getPlatformElevation.js
src/styles/getPlatformElevation.web.js

Demo app in [https://github.com/dalcib/react-native-material-ui-web-app](https://github.com/dalcib/react-native-material-ui-web-app)

Make react-native-material-ui compatible with react-native-web

---

src/ActionButton/ActionButton.react.js
src/Avatar/Avatar.react.js
src/BottomNavigation/BottomNavigation.react.js
src/BottomNavigation/BottomNavigationAction.react.js
src/Button/Button.react.js
src/IconToggle/IconToggle.react.js
src/RippleFeedback/RippleFeedback.react.js
src/Snackbar/Snackbar.react.js
src/Toolbar/Toolbar.react.js
src/styles/getPlatformElevation.android.js
src/styles/getPlatformElevation.ios.js
src/styles/getPlatformElevation.web.js
src/styles/getTheme.js
src/utils/index.js

References https://github.com/xotahal/react-native-material-ui/pull/148.

Fix ViewPropTypes error

---

src/ListItem/ListItem.react.js

Update `ListItem` props with missing `menu` props.

Update listitem props

---

README.md
docs/Divider.md
docs/Drawer.md
docs/Icon.md
docs/IconToggle.md
docs/ListItems.md
docs/RadioButton.md
docs/Subheader.md

Just documented the basic usage and APIs of the components that remained undocumented.

Updated Docs

---

src/Drawer/HeaderAccount.react.js

This fixes a warning with the PropTypes

fix: PropTypes of Drawer.HeaderAccount

---

src/Card/Card.react.js

Allows the card to update styles when the component has already been mounted

---

README.md

Fix ListItems doc url

---

src/IconToggle/IconToggle.react.js

fix(iconToggle): Wrong value passed to style prop

---

docs/Subheader.md

i just noticed the error in the word

error corrected

---

src/ListItem/ListItem.react.js

Based on the issues #250, #270, #298, and from what I myself encountered after started using the Drawer, this warning was always shown in the app: 
```
Warning: Failed prop type: Invalid props.leftElement key `color` supplied to `ListItem`.
```
As @aburai suggested in #250, leftElement and rightElement, not being set to `<View />`, they should be `PropTypes.style`, not `ViewPropTypes.style`.
It seems that the default style of the `props.styles.leftElement` contains a `color` property that is blocked by the default set `ViewPropTypes.style`.
Full warning text: 
```
Warning: Failed prop type: Invalid props.leftElement key `color` supplied to `ListItem`.
Bad object: {
"color": "#2196f3"
}
Valid keys: [
"display",
"width",
"height",
"start",
"end",
"top",
"left",
"right",
"bottom", …
```

Fix Warning Invalid key color to ListItem

---

README.md

Fixed the link about the animations for Android.

Fixed the link about the animations for Android

---

src/Badge/Badge.react.js

Fix Badge style proptype

---

src/Toolbar/RightElement.react.js
src/Toolbar/Toolbar.react.js

Add option to change the Toolbar searhcable icon.

Changeable search icon

---

src/Snackbar/Snackbar.react.js
src/styles/getTheme.js

We need to set custom 'bottom' style for example when a keyboard is shown etc.

Allow user to set custom snackbar's position, fix updating styles

---

docs/Snackbar.md

Documentation

---

docs/Components.md

Add link for SnackBar documentation.
I`m using this project, really apreciate all work done and i`m hope i can help with this little fix =)

Add link to Snackbar component doc

---

docs/ActionButton.md

Improve ActionBar documentation so developers can add their custom styles
PR adds styles documentation for both `toolbar` and `speed dial`

Improve ActionBar documentation
